# Generated by Django 5.0.4 on 2024-05-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_Name',
            new_name='category_name',
        ),
    ]
