# Generated by Django 5.0.4 on 2024-05-12 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_rename_category_name_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('product_description', models.CharField(max_length=255, null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_image', models.ImageField(null=True, upload_to='image/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.category')),
            ],
        ),
    ]
